version: 2

updates:
    - package-ecosystem: "cargo"
      directory: "/agde"
      schedule:
          interval: "daily"
    - package-ecosystem: "cargo"
      directory: "/den"
      schedule:
          interval: "daily"
