[workspace]
resolver = "2"

members = [
    "agde",
    "den",
    "agde-tokio",
    "agde-io",
    "agde-web",
]

# profile for binary sub-crates.
[profile.distribution]
inherits = "release"
lto = true
strip = true
