[package]
name = "den"
version = "0.1.0"
authors = ["Icelk <main@icelk.dev>"]
edition = "2021"
rust-version = "1.56"
description = "A general delta encoded network difference algorithm."
readme = "README.md"
# homepage = "https://icelk.dev/den/"
repository = "https://github.com/Icelk/agde/"
license = "LGPL-3.0-or-later"
keywords = ["diff", "rdiff", "rsync"]
categories = ["algorithms"]

[dependencies]
