name: agde-io CI

on:
    push:
        paths:
            - "agde-io/**"
            - "agde/**"
            - "Cargo.toml"
            - ".github/workflows/agde-io.yml"

env:
    CARGO_TERM_COLOR: always

defaults:
    run:
        working-directory: agde-io

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - name: Checking out sources
              uses: actions/checkout@v3
            - run: rustup toolchain install stable
            - uses: Swatinem/rust-cache@v2
            - name: Checking formatting
              run: cargo fmt --check
            - name: Checking lints
              run: cargo clippy --all-targets -- -D warnings
            - name: Checking lints with all features
              run: cargo clippy --all-targets --all-features -- -D warnings
            - name: Testing project
              run: cargo test
            - uses: Icelk/rustdoc-link-check@v2
              with:
                  working-directory: agde-io
                  private: true
