name: agde-tokio CI

on:
    push:
        paths:
            - "agde-tokio/**"
            - "agde/**"
            - ".github/workflows/agde-tokio.yml"

env:
    CARGO_TERM_COLOR: always

defaults:
    run:
        working-directory: agde-tokio

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - name: Checking out sources
              uses: actions/checkout@v2
            - name: Installing Rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
            - uses: Swatinem/rust-cache@v1
            - name: Checking formatting
              run: cargo fmt -- --check --color always
            - name: Checking lints
              run: cargo clippy --all-targets -- -D warnings
            - name: Checking lints with all features
              run: cargo clippy --all-targets --all-features -- -D warnings
            - name: Testing project
              run: cargo test
            - uses: Icelk/rustdoc-link-check@v1
              with:
                  working-directory: agde-tokio
                  private: true

    build:
        needs: [check]
        runs-on: ubuntu-latest
        steps:
            - name: Checking out sources
              uses: actions/checkout@v1
            - name: Installing Rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  profile: minimal
            - uses: Swatinem/rust-cache@v1
            - name: Compiling
              run: cargo rustc --profile distribution
            - name: Upload bin artefact
              uses: actions/upload-artifact@v2
              with:
                  name: agde-tokio
                  path: target/distribution/agde-tokio
