name: Den CI

on:
    push:
        paths:
            - "den/**"
            - ".github/workflows/den.yml"

env:
    CARGO_TERM_COLOR: always

defaults:
    run:
        working-directory: den

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - name: Checking out sources
              uses: actions/checkout@v2
            - name: Installing Rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
            - uses: Swatinem/rust-cache@v1
            - name: Checking formatting
              run: cargo fmt -- --check --color always
            - name: Checking lints
              run: cargo clippy --all-targets -- -D warnings
            - name: Testing project
              run: cargo test
            - uses: Icelk/rustdoc-link-check@v1
              with:
                  working-directory: den
                  private: true
